### ISSUE TITLE
[Epic] Port integrations tests from Pulumi and Pulumi Java

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/besom#237]
- [ ] https://github.com/pulumi/pulumi/blob/master/tests/about_test.go and friends
- [x] https://github.com/pulumi/pulumi/blob/master/tests/integration/empty/nodejs/Pulumi.yaml and some more
- [x] https://github.com/pulumi/pulumi/blob/master/tests/examples/secrets/index.ts
- [x] ...find more tests to port upstream...

**Comment by pawelprazak** [comment]
closed in favor of #73
