### ISSUE TITLE
[Epic] Add Automation API

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/besom#254]
We are missing the programmatic interaction API.

Steps we might want to make:
- [ ] Add basic internal implementation for CLI interactions to `experimental` package that can be reused by integration tests
- [ ] Add basic internal implementation for `Inline` using [Java PoC as a reference](https://github.com/pulumi/pulumi-java/pull/1180)
- [ ] Design Besom-flavour API
- [ ] Implement the Besom-flavour API in `experimental` package for minimal API coverage
- [ ] Implement missing parts of API (remote, git, etc.)
- [ ] Port integration tests for upstream
- [ ] Move out of `experimental` package and release to the public

**Comment by pawelprazak** [comment]
Note to self - remember to port new features, esp.:
https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v3/go/auto#InstallPulumiCommand
