### ISSUE TITLE
[Epic] Write tests for everything

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#73]
Writing comprehensive tests is crucial for code reliability and maintainability.

Port tests from upstream:
- [x] com.pulumi.serialization.internal.PropertiesSerializerTests
- [x] com.pulumi.serialization.internal.ReSerializerTest
- [ ] https://github.com/pulumi/pulumi/tree/master/tests/integration/deleted_with
- [ ] https://github.com/pulumi/pulumi/tree/master/tests/integration/delete_before_create
- [ ] https://github.com/pulumi/pulumi/blob/master/tests/integration/stack_parenting
- [ ] https://github.com/pulumi/pulumi/blob/master/tests/integration/protect_resources/protect_test.go
- [ ] https://github.com/pulumi/pulumi/blob/master/tests/integration/custom_timeouts/custom_timeouts_test.go
- [ ] https://github.com/pulumi/pulumi/blob/master/tests/remote_test.go
- [ ] https://github.com/pulumi/pulumi/blob/151558f7f2f0117fb1acfe7dbad00f46ca1bb5f8/sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go, https://github.com/pulumi/pulumi/blob/151558f7f2f0117fb1acfe7dbad00f46ca1bb5f8/sdk/python/cmd/pulumi-language-python/language_test.go
- [ ] ...find more tests to port...

**Comment by pawelprazak** [comment]
related: #237

**Comment by pawelprazak** [comment]
related: #381
