### ISSUE TITLE
[Epic] Clean up TODOs in Codegen

### ISSUE THREAD

**Issue by lbialy** [VirtusLab/besom#77]
Review and address the existing TODOs in Codegen.

**Comment by pawelprazak** [comment]
TODOs:
- [ ] revert to throwing when upstream resolves https://github.com/pulumi/pulumi/issues/15024
- [ ] implement docs - scaladoc generation
- [ ] truncated file names with a suffix might still potentially clash with each other
- [ ] Handle allowedPackageNames (#342)
- [ ] Handle stateInputs 
- [ ] Handle aliases (#44)
- [ ] Find some workaround to enable passing the remaining arguments (>253)
- [ ] we might need to do proper URL un-escaping i TypeMapper
- [ ] when translating from schema to Scala, we should refactor to use proper ADTs (might be related to PCL)
